CREATE TABLE PLAYER  (
	PLAYER_ID VARCHAR(30) NOT NULL PRIMARY KEY ,
	LAST_NAME VARCHAR(30) NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	POSITION VARCHAR(30) NOT NULL,
	BIRTH_YEAR NUMBER NOT NULL,
	DEBUT_YEAR NUMBER NOT NULL
);